name: example

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.0.0

  json_serializable: ^3.2.0

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  # Used by tests. Not required to use `json_serializable`.
  test: ^1.6.0

dependency_overrides:
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
  # Normally pubspec_parse would be constrained to <1.0.0 because of this
  # package's constraint on json_annotation ^3.0.0, but because json_annotation
  # is also overridden here, that does not happen, and pubspec_parse would
  # otherwise resolve to v1 which will fail. To avoid that issue, we override
  # pubspec_parse here, but note that this is not representative of a consumer
  # would actually need to do – depending on json_annotation ^3.0.0 is
  # sufficient for consumers.
  pubspec_parse: <1.0.0
