# See https://github.com/google/mono_repo.dart for details on this file
stages:
- analyzer_and_format:
  - group:
    - analyze: --fatal-warnings --fatal-infos .
    dart: [stable]
  - group:
    - format
    - analyze: --fatal-warnings .
    dart: [2.13.4]
